train:
  batch: 1
  lr: 1e-3
  device: 'cuda'
  total_epoch: 200
  workers: 8
  weight_decay: 0.05
  warmup_epoch: 20


vqvaemesh:
  num_embeddings: 512
  embedding_dim: 9
  commitment_cost: 0.25
  decay: 0.99
  num_quantizer: 1
  

modelconv:
  batch: 1
  connection_folder: body_models/ConnectionMatrices/
  initial_connection_fn: body_models/ConnectionMatrices/_pool0.npy
  connection_layer_lst: ["pool0", "pool1", "pool2","pool3", "pool4", "pool5", "pool6","unpool6", "unpool5","unpool4","unpool3","unpool2","unpool1", "unpool0"]
  channel_lst: [ 32, 32,  64, 64, 128, 128, 9, 128, 128,64, 64,32, 32,3]
  weight_num_lst: [9,0, 9,0, 9,0, 9,9, 0,9,0,9,0,9]
  residual_rate_lst: [0,1,  0,1,  0,1,  0,0,  1,0,  1,0,  1,0]
  
  
model:
  seq_length: 54
  emb_dim: 1024
  encoder_layer: 12
  encoder_head: 4
  decoder_layer: 4
  decoder_head: 4
  num_embeddings: 512
  dim_tokens: 512
  masking: 'scheduled'
  cond_length: 49
  cond_dim: 720
  cond_dropout: 0


backbone:
  type: hrnet
  pretrained: body_models/pose_hrnet_w48.pth

  
training_data:
  file: 'configs/config_cvqmae/coco_train.txt'
  
validation_data:
  file: 'configs/config_cvqmae/3dpw_validation.txt'

test_data:
  file: 'configs/config_cvqmae/3dpw_test.txt'

resume:
  path: 'checkpoint/CVQMAE/mega_hrnet'
  # path: 'checkpoint/CVQMAE/2026-3-31/23-34-3DPW-EMDB/model_checkpoint'
  # path: 'checkpoint/CVQMAE/2026-3-31/23-34-3DPW-EMDB/model_best_loss'
  # path: 'checkpoint/CVQMAE/2026-4-1/19-45/model_best_2d'
  # path: 'checkpoint/CVQMAE/2026-4-1/21-3/model_best_2d'

# demo_generate.py 参数
mode: 'confidence_vis'
# input_path: '/home/zzb/pydata/recons/MEGA/demo_data/input/3dpw_occ'
input_path: '/home/zzb/pydata/recons/MEGA/demo_data/input/dataset_samples/emdb_occ_mesh'
# input_path: '/home/zzb/pydata/recons/MEGA/demo_data/input/dataset_samples/emdb_occ2'
output_dir: '/home/zzb/pydata/recons/MEGA/demo_out/step_vis/emdb_occ_s5_mesh_t1'
steps: 5
temp: 1.0
sample_size: 10
max_samples: null
sample_idx: 0

# 置信度可视化
# python demo_generate.py --mode confidence_vis --steps 50 --temp 1.0

# # 步骤可视化（需要渲染模块）
# python demo_generate.py --mode step_vis --steps 5 --temp 1.0 --sample_idx 0

# # 多样本可视化（需要渲染模块）
# python demo_generate.py --mode samples_vis --steps 5 --temp 1.0 --sample_size 10
